# version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
      SECRET_KEY: supersecret
      UPLOAD_DIR: /app/storage/uploads
    volumes:
      - ./backend/app/storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend      
volumes:
  db_data:
